config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: 'home#index'
  resources :students
  resources :high_schools
  resources :addresses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street, :subdivision, :city, :province, :region)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
    def long_address(a)
        [a.street, a.subdivision, a.city, a.province, a.region].join(', ')
    end
    def short_address(a)
        [a.street, a.city].join(', ')
    end
end

app/views/addresses/_form.html.erb
<%= form_with(model: address, local: true) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :subdivision %>
    <%= form.text_field :subdivision %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :province %>
    <%= form.text_field :province %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Street</th>
      <th>Subdivision</th>
      <th>City</th>
      <th>Province</th>
      <th>Region</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.street %></td>
        <td><%= address.subdivision %></td>
        <td><%= address.city %></td>
        <td><%= address.province %></td>
        <td><%= address.region %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>Subdivision:</strong>
  <%= @address.subdivision %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>Province:</strong>
  <%= @address.province %>
</p>

<p>
  <strong>Region:</strong>
  <%= @address.region %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>