config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: 'home#index'
  resources :students
  resources :high_schools
  resources :addresses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/high_school.rb
class HighSchool < ApplicationRecord
    has_many :year_graduateds
    has_many :students, through: :year_graduateds
    
    belongs_to :address
end

app/controllers/high_schools_controller.rb
class HighSchoolsController < ApplicationController
  before_action :set_high_school, only: [:show, :edit, :update, :destroy]

  # GET /high_schools
  # GET /high_schools.json
  def index
    @high_schools = HighSchool.all
  end

  # GET /high_schools/1
  # GET /high_schools/1.json
  def show
  end

  # GET /high_schools/new
  def new
    @high_school = HighSchool.new
  end

  # GET /high_schools/1/edit
  def edit
  end

  # POST /high_schools
  # POST /high_schools.json
  def create
    @high_school = HighSchool.new(high_school_params)

    respond_to do |format|
      if @high_school.save
        format.html { redirect_to @high_school, notice: 'High school was successfully created.' }
        format.json { render :show, status: :created, location: @high_school }
      else
        format.html { render :new }
        format.json { render json: @high_school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /high_schools/1
  # PATCH/PUT /high_schools/1.json
  def update
    respond_to do |format|
      if @high_school.update(high_school_params)
        format.html { redirect_to @high_school, notice: 'High school was successfully updated.' }
        format.json { render :show, status: :ok, location: @high_school }
      else
        format.html { render :edit }
        format.json { render json: @high_school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /high_schools/1
  # DELETE /high_schools/1.json
  def destroy
    @high_school.destroy
    respond_to do |format|
      format.html { redirect_to high_schools_url, notice: 'High school was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_high_school
      @high_school = HighSchool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def high_school_params
      params.require(:high_school).permit(:name, :address_id)
    end
end

app/helpers/high_schools_helper.rb
module HighSchoolsHelper
end

app/views/high_schools/_form.html.erb
<%= form_with(model: high_school, local: true) do |form| %>
  <% if high_school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(high_school.errors.count, "error") %> prohibited this high_school from being saved:</h2>

      <ul>
      <% high_school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address_id %>
    <%= form.number_field :address_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/high_schools/edit.html.erb
<h1>Editing High School</h1>

<%= render 'form', high_school: @high_school %>

<%= link_to 'Show', @high_school %> |
<%= link_to 'Back', high_schools_path %>

app/views/high_schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>High Schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @high_schools.each do |high_school| %>
      <tr>
        <td><%= high_school.name %></td>
        <td><%= high_school.address_id %></td>
        <td><%= link_to 'Show', high_school %></td>
        <td><%= link_to 'Edit', edit_high_school_path(high_school) %></td>
        <td><%= link_to 'Destroy', high_school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New High School', new_high_school_path %>

app/views/high_schools/new.html.erb
<h1>New High School</h1>

<%= render 'form', high_school: @high_school %>

<%= link_to 'Back', high_schools_path %>

app/views/high_schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @high_school.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @high_school.address_id %>
</p>

<%= link_to 'Edit', edit_high_school_path(@high_school) %> |
<%= link_to 'Back', high_schools_path %>